services:
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    # declare bind mount
    volumes:
      # location in host : location in container
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      # preserve changes from DB w/in container to outside of container
      - ./mongo_data:/data/db